#!/bin/bash
set -exou pipefail
# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "=-=-=-=-= Building Images =-=-=-=-="
docker buildx build \
  --platform linux/arm64,linux/amd64 \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --build-arg VERSION="$(xargs < VERSION)" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --tag "${DOCKER_REPO}:${DOCKER_TAG}" \
  --tag "${IMAGE_NAME}" .
